language: java
addons:
  sonarcloud:
    organization: "dimyriy-github"

script:
- mvn clean test install --activate-profiles travis-ci sonar:sonar jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
